services:
  bot:
    build: .
    volumes:
      - ./bot:/bot
    env_file:
      - .env
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=weather_bot
      - DB_HOST=pgdb
      - DB_PORT=5432
    command: >
      sh -c "alembic upgrade head
             python3 main.py"
    depends_on:
      pgdb:
        condition: service_healthy

  pgdb:
    image: postgres
    environment:
      - POSTGRES_DB=weather_bot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d weather_bot"]
      interval: 2s
      timeout: 2s
      retries: 5
    volumes: 
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: